apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis6-deployment
spec:
  selector:
    matchLabels:
      app: redis6
  template:
    metadata:
      labels:
        app: redis6
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: vm
                operator: In
                values:
                - RF  # 假设VMA是目标节点的标签
